name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install npm
      run: |
        ls -la
        npm install
        ls -la
         
    - name: Run build
      run: npm build
