#Every changes in MASTER will deploy to marketplase with next patch number
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
           
    - name: Setup VSCE
      run : npm install vsce
      
    - name: Commit changes
      run: |
        git config user.email "raven03160@gmail.com"
        git config user.name "Veniamin Rakov"
        git commit -m "Update files by Deploy Action"

    - name: Deploy to Marketplace
      run : node_modules/vsce/out/vsce publish patch -p ${{ secrets.MARKETPLACE_TOKEN }}
