#Every changes in MASTER will deploy to marketplase with next patch number
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
           
    - name: Setup VSCE
      run : npm install vsce
      
    - name: Save changes in packages in master
      uses: actions/commit

    - name: Deploy to Marketplace
      run : node_modules/vsce/out/vsce publish patch -p ${{ secrets.MARKETPLACE_TOKEN }}
