#Every changes in MASTER will deploy to marketplase with next patch number
name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install npm
      run : npm install
           
    - name: Setup VSCE
      run : npm install vsce

    - name: Deploy to Marketplace
      run : |
        ls -la
        cd ..
        ls -la /RSL/RSL
